server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/baangn
    username: baangn-user
    password: password

oauth:
  kakao:
    base-url: https://kapi.kakao.com
aws:
  access-key: test
  secret-key: test
  bucket: test
  region: ap-northeast-2
